// Generated by CoffeeScript 1.6.3
(function() {
  var app, coffee, compile, css, database, diary, express, fs, html, http, jqm, jquery, js, material, mobile, nib, nodejs, others, path, routes, rwd, stylus;

  express = require("express");

  routes = require("./routes");

  html = require("./routes/html");

  css = require("./routes/css");

  rwd = require("./routes/rwd");

  js = require("./routes/js");

  jquery = require("./routes/jquery");

  mobile = require("./routes/mobile");

  others = require("./routes/others");

  jqm = require("./routes/jqm");

  nodejs = require("./routes/nodejs");

  database = require("./routes/database");

  material = require("./routes/material");

  diary = require("./routes/diary");

  http = require("http");

  fs = require("fs");

  stylus = require("stylus");

  nib = require("nib");

  coffee = require("coffee-script");

  path = require("path");

  app = express();

  app.use(express.basicAuth("nakano", "nakano"));

  app.set("port", process.env.PORT || 3000);

  app.set("views", __dirname + "/views");

  app.set("view engine", "jade");

  app.use(express.favicon());

  app.use(express.logger("dev"));

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.use(express.cookieParser("your secret here"));

  app.use(express.session());

  app.use(app.router);

  compile = function(str, path) {
    return stylus(str).set("filename", path).set("compress", true).use(nib());
  };

  app.use(stylus.middleware({
    src: __dirname + "/public",
    compile: compile
  }));

  app.use(express["static"](path.join(__dirname, "public")));

  /*
  app.use require("stylus").middleware(
  	src: __dirname + "/views"
  	dest: __dirname + "/public"
  )
  */


  /*
  app.use require("connect-coffee-script")(
  	src: __dirname + "/views"
  	dest: __dirname + "/public"
  	bare: true
  )
  */


  if ("development" === app.get("env")) {
    app.use(express.errorHandler());
  }

  app.get("/", routes.index);

  app.get("/html/:id", html.html);

  app.get("/_css/:id", css.css);

  app.get("/rwd/:id", rwd.rwd);

  app.get("/bootstrap/:id", rwd.bootstrap);

  app.get("/jquery/:id", jquery.jquery);

  app.get("/jqueryui/:id", jquery.jqueryui);

  app.get("/jqm/:id", jqm.jqm);

  app.get("/mobile/:id", mobile.mobile);

  app.get("/nodejs/:id", nodejs.nodejs);

  app.get("/mysql/:id", database.mysql);

  app.get("/mongodb/:id", database.mongodb);

  app.get("/redis/:id", database.redis);

  app.get("/angular/:id", js.angular);

  app.get("/requirejs/:id", js.requirejs);

  app.get("/underscore/:id", js.underscore);

  app.get("/jasmine/:id", js.jasmine);

  app.get("/others/:id", others.others);

  app.get("/diary/:id", diary.diary);

  app.get("/js-:id:format", js.js);

  app.get("/webapi-:id:format", js.webapi);

  app.get("/html5api-:id:format", js.html5);

  app.get("/canvas/:id", js.canvas);

  app.get("/enchant/:id", js.enchant);

  app.get("/library/:id", js.library);

  app.get("/jsrecipe-:id", js.recipe);

  app.get("/material:id:format", material.material);

  app.get("/cordova/:id", js.cordova);

  app.get("/material/git-:id", material.git);

  app.get("/material/vagrant-:id", material.vagrant);

  app.post("/xml-:id", js.webapiXML);

  http.createServer(app).listen(app.get("port"), function() {
    return console.log("Express server listening on port " + app.get("port"));
  });

}).call(this);
