// Generated by CoffeeScript 1.6.3
(function() {
  var app, coffee, css, diary, express, fs, html, http, jqm, jquery, js, material, mobile, nodejs, others, path, routes, rwd;

  express = require("express");

  routes = require("./routes");

  html = require("./routes/html");

  css = require("./routes/css");

  rwd = require("./routes/rwd");

  js = require("./routes/js");

  jquery = require("./routes/jquery");

  mobile = require("./routes/mobile");

  others = require("./routes/others");

  jqm = require("./routes/jqm");

  nodejs = require("./routes/nodejs");

  material = require("./routes/material");

  diary = require("./routes/diary");

  http = require("http");

  fs = require("fs");

  coffee = require("coffee-script");

  path = require("path");

  app = express();

  app.use(express.basicAuth("nakano", "nakano"));

  app.set("port", process.env.PORT || 3000);

  app.set("views", __dirname + "/views");

  app.set("view engine", "ejs");

  app.use(express.favicon());

  app.use(express.logger("dev"));

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.use(express.cookieParser("your secret here"));

  app.use(express.session());

  app.use(app.router);

  app.use(express["static"](path.join(__dirname, "public")));

  app.use(require("stylus").middleware({
    src: __dirname + "/views",
    dest: __dirname + "/public"
  }));

  app.use(require("connect-coffee-script")({
    src: __dirname + "/views",
    dest: __dirname + "/public",
    bare: true
  }));

  if ("development" === app.get("env")) {
    app.use(express.errorHandler());
  }

  app.get("/", routes.index);

  app.get("/html/:id", html.html);

  app.get("/_css/:id", css.css);

  app.get("/rwd-id", rwd.rwd);

  app.get("/jquery/:id", jquery.jquery);

  app.get("/jqm:id", jqm.jqm);

  app.get("/mobile:id:format", mobile.mobile);

  app.get("/nodejs:id:format", nodejs.nodejs);

  app.get("/others/:id", others.others);

  app.get("/diary/:id", diary.diary);

  app.get("/js-:id", js.js);

  app.get("/webapi-:id", js.webapi);

  app.get("/html5api-:id", js.html5);

  app.get("/canvas:id:format", js.canvas);

  app.get("/enchant-:id", js.enchant);

  app.get("/library:id:format", js.library);

  app.get("/jsrecipe-:id", js.recipe);

  app.get("/material-:id", material.material);

  app.get("/cordova:id:format", material.cordova);

  app.get("/material/git-:id", material.git);

  app.get("/material/vagrant-:id", material.vagrant);

  app.post("/xml-:id", js.webapiXML);

  http.createServer(app).listen(app.get("port"), function() {
    return console.log("Express server listening on port " + app.get("port"));
  });

}).call(this);
