// Generated by CoffeeScript 1.6.3
(function() {
  var config;

  config = require("../config.json");

  exports.html = function(req, res) {
    return res.render("html/html" + req.params.id + ".jade", {
      title: config.title,
      instructor: config.instructor,
      pretty: true
    });
  };

}).call(this);
