// Generated by CoffeeScript 1.6.3
(function() {
  var define;

  define = require("../models/define");

  exports.index = function(req, res) {
    res.render("index.jade", {
      title: define.title,
      instructor: define.instructor,
      pretty: true
    });
  };

}).call(this);
