// Generated by CoffeeScript 1.6.3
(function() {
  var config;

  config = require("../config.json");

  exports.js = function(req, res) {
    return res.render("js/js-" + req.params.id, {
      title: config.title,
      instructor: config.instructor
    });
  };

  exports.enchant = function(req, res) {
    return res.render("js/enchant/enchant-" + req.params.id, {
      title: config.title,
      instructor: config.instructor
    });
  };

  exports.webapi = function(req, res) {
    return res.render("js/webapi/webapi-" + req.params.id, {
      title: config.title,
      instructor: config.instructor
    });
  };

  exports.webapiXML = function(req, res) {
    res.header("Content-Type", "text/xml");
    return res.render("js/webapi/xml-" + req.params.id, {});
  };

  exports.html5 = function(req, res) {
    return res.render("js/html5/html5-" + req.params.id, {
      title: config.title,
      instructor: config.instructor
    });
  };

  exports.canvas = function(req, res) {
    return res.render("js/canvas/canvas" + req.params.id + req.params.format, {
      title: config.title,
      instructor: config.instructor,
      pretty: true
    });
  };

  exports.library = function(req, res) {
    return res.render("js/library/library" + req.params.id + req.params.format, {
      title: config.title,
      instructor: config.instructor,
      pretty: true
    });
  };

  exports.recipe = function(req, res) {
    return res.render("js/recipe/recipe1-" + req.params.id, {
      title: config.title,
      instructor: config.instructor
    });
  };

}).call(this);
