// Generated by CoffeeScript 1.7.1
(function() {
  var define;

  define = require("../libs/define");

  exports.material = function(req, res) {
    return res.render("material/material-" + req.params.id + req.params.format, {
      title: define.title,
      instructor: define.instructor,
      pretty: true
    });
  };

}).call(this);
