// Generated by CoffeeScript 1.6.3
(function() {
  var config;

  config = require("../config.json");

  exports.material = function(req, res) {
    return res.render("material/material-" + req.params.id, {
      title: config.title,
      instructor: config.instructor
    });
  };

  exports.cordova = function(req, res) {
    return res.render("material/cordova/cordova" + req.params.id + req.params.format, {
      title: config.title,
      instructor: config.instructor,
      pretty: true
    });
  };

  exports.git = function(req, res) {
    return res.render("material/git/git-" + req.params.id, {
      title: config.title,
      instructor: config.instructor
    });
  };

  exports.vagrant = function(req, res) {
    return res.render("material/vagrant/vagrant-" + req.params.id, {
      title: config.title,
      instructor: config.instructor
    });
  };

}).call(this);
