// Generated by CoffeeScript 1.6.3
(function() {
  var config;

  config = require("../config.json");

  exports.mobile = function(req, res) {
    return res.render("mobile/mobile" + req.params.id + req.params.format, {
      title: config.title,
      instructor: config.instructor,
      pretty: true
    });
  };

}).call(this);
