// Generated by CoffeeScript 1.7.1
(function() {
  var define;

  define = require("../libs/define");

  exports.mobile = function(req, res) {
    return res.render("mobile/mobile" + req.params.id, {
      title: define.title,
      instructor: define.instructor,
      pretty: true
    });
  };

}).call(this);
