// Generated by CoffeeScript 1.6.3
(function() {
  var define;

  define = require("../models/define");

  exports.nodejs = function(req, res) {
    return res.render("nodejs/nodejs" + req.params.id + ".jade", {
      title: define.title,
      instructor: define.instructor,
      pretty: true
    });
  };

}).call(this);
