// Generated by CoffeeScript 1.7.1
(function() {
  var define;

  define = require("../libs/define");

  exports.others = function(req, res) {
    return res.render("others/others" + req.params.id, {
      title: define.title,
      instructor: define.instructor,
      pretty: true
    });
  };

  exports.git = function(req, res) {
    return res.render("others/git/git" + req.params.id, {
      title: define.title,
      instructor: define.instructor
    });
  };

  exports.vagrant = function(req, res) {
    return res.render("others/vagrant/vagrant" + req.params.id, {
      title: define.title,
      instructor: define.instructor
    });
  };

  exports.genymotion = function(req, res) {
    return res.render("others/genymotion/genymotion" + req.params.id, {
      title: define.title,
      instructor: define.instructor
    });
  };

}).call(this);
